# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 20:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interest', models.CharField(choices=[(('Vo',), 'Vocal'), ('Ins', 'Instrumental')], default=('Vo',), max_length=3)),
                ('Genre', models.CharField(choices=[(('Fo',), 'Folk'), (('Ja',), 'Jazz'), (('Hi',), 'HipHop'), (('Rap',), 'Rapping'), (('Cl',), 'Classical'), (('Ed',), 'EDM'), (('Ro',), 'Rock'), (('Di',), 'Disco')], default=('Cl',), max_length=3)),
                ('Associated_with', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
