# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeoffapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Interest',
            field=models.CharField(choices=[((b'Vo',), b'Vocal'), ((b'Ins',), b'Instrumental')], default=(b'Vo',), max_length=3),
        ),
    ]
