# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeoffapp', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='File',
            field=models.FileField(blank=True, upload_to=b'audio'),
        ),
    ]
