# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeoffapp', '0006_auto_20171028_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Status',
            field=models.CharField(choices=[((b'Mentor',), b'Mentor'), ((b'MENTEE',), b'Mentee')], default=(b'Vocal',), max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Genre',
            field=models.CharField(choices=[((b'Folk',), b'Folk'), ((b'Jazz',), b'Jazz'), ((b'HipHop',), b'HipHop'), ((b'Rapping',), b'Rapping'), ((b'Classical',), b'Classical'), ((b'EDM',), b'EDM'), ((b'Rock',), b'Rock'), ((b'Disco',), b'Disco')], default=(b'Classical',), max_length=3),
        ),
    ]
