# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeoffapp', '0008_auto_20171028_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Score',
            field=models.IntegerField(default=0),
        ),
    ]
